site_name: Locations
site_url: https://marcussacapuces91.github.io/locations/
site_description: Visit locations
site_author: M. SIBERT

repo_url: https://github.com/Marcussacapuces91/locations/
edit_uri: blob/master/docs/

theme:
#  name: mkdocs
  name: material
#  color_mode: auto
#  user_color_mode_toggle: true
#  locale: fr
#  analytics: {gtag: 'G-274394082'}
#  highlightjs: true
#  hljs_languages:
#    - yaml
#    - django

#nav:
#  - Home: index.md
#  - Getting Started: getting-started.md
#  - User Guide: user-guide/
#  - Developer Guide: dev-guide/
#  - About:
#    - Release Notes: about/release-notes.md
#    - Contributing: about/contributing.md
#    - License: about/license.md

extra_css:
  - css/extra.css

#exclude_docs: |
#  *.py

#markdown_extensions:
#  - toc:
#      permalink: 
#  - attr_list
#  - def_list
#  - tables
#  - pymdownx.highlight:
#      use_pygments: false
#  - pymdownx.snippets
#  - pymdownx.superfences
#  - callouts
#  - mdx_gh_links:
#      user: mkdocs
#      repo: mkdocs
#  - mkdocs-click

copyright: Copyright &copy; 2025 <a href="https://lab-allen.fr">M. SIBERT</a>.

#hooks:
#  - docs/hooks.py

#plugins:
#  - search
#  - redirects:
#      redirect_maps:
#        user-guide/plugins.md: dev-guide/plugins.md
#        user-guide/custom-themes.md: dev-guide/themes.md
#        user-guide/styling-your-docs.md: user-guide/choosing-your-theme.md
#  - autorefs
#  - literate-nav:
#      nav_file: README.md
#      implicit_index: true
#  - mkdocstrings:
#      handlers:
#        python:
#          options:
#            docstring_section_style: list
#            members_order: source
#            show_root_heading: true
#            show_source: false
#            show_signature_annotations: true

#watch:
#  - mkdocs
