site_name: Locations
site_url: https://marcussacapuces91.github.io/locations/
site_description: Visit locations
site_author: M. SIBERT

repo_url: https://github.com/Marcussacapuces91/locations/
edit_uri: blob/master/docs/

theme:
  name: material
  color_mode: auto
  user_color_mode_toggle: true
  language: fr
  # logo: # préciser le chemin vers le logo dans l'entête
  # favicon: images/favicon.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - toc.follow
    
    
  
#  color_mode: auto
#  user_color_mode_toggle: true
#  locale: fr
#  analytics: {gtag: 'G-274394082'}
#  highlightjs: true
#  hljs_languages:
#    - yaml
#    - django

#nav:
#  - Home: index.md
#  - Getting Started: getting-started.md
#  - User Guide: user-guide/
#  - Developer Guide: dev-guide/
#  - About:
#    - Release Notes: about/release-notes.md
#    - Contributing: about/contributing.md
#    - License: about/license.md

extra_css:
  - css/extra.css

#exclude_docs: |
#  *.py

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

copyright: Copyright &copy; 2025 <a href="https://lab-allen.fr">M. SIBERT</a>.

#hooks:
#  - docs/hooks.py

#plugins:
#  - search
#  - redirects:
#      redirect_maps:
#        user-guide/plugins.md: dev-guide/plugins.md
#        user-guide/custom-themes.md: dev-guide/themes.md
#        user-guide/styling-your-docs.md: user-guide/choosing-your-theme.md
#  - autorefs
#  - literate-nav:
#      nav_file: README.md
#      implicit_index: true
#  - mkdocstrings:
#      handlers:
#        python:
#          options:
#            docstring_section_style: list
#            members_order: source
#            show_root_heading: true
#            show_source: false
#            show_signature_annotations: true

#watch:
#  - mkdocs
